<?php

return [
    'sections' => [
        'general' => [
            'label' => 'General',
            'sidebar_label' => null,
            'order' => 10,
            'contexts' => ['desktop', 'search'],
        ],
        'demo' => [
            'label' => 'Demo',
            'sidebar_label' => null,
            'order' => 15,
            'contexts' => ['desktop', 'search'],
        ],
        'management' => [
            'label' => 'Management',
            'sidebar_label' => 'Management',
            'order' => 20,
            'contexts' => ['desktop', 'search'],
        ],
        'settings' => [
            'label' => 'Settings',
            'sidebar_label' => 'Settings',
            'order' => 30,
            'contexts' => ['desktop', 'search'],
        ],
        'inventory' => [
            'label' => 'Inventory',
            'sidebar_label' => 'Inventory',
            'order' => 40,
            'contexts' => ['desktop', 'search'],
        ],
    ],

    'items' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'icon' => 'bx-home-smile',
            'route' => 'home',
            'route_params' => [],
            'active_patterns' => ['home'],
            'permission' => null,
            'section' => 'general',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Main dashboard overview',
                'keywords' => ['dashboard', 'home', 'main', 'overview'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'form-demo-index',
            'label' => 'Form Demo',
            'icon' => 'bx-detail',
            'route' => 'form-demo.index',
            'route_params' => [],
            'active_patterns' => ['form-demo.*'],
            'permission' => null,
            'section' => 'demo',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Live examples for reusable Blade form components',
                'keywords' => ['form', 'demo', 'components', 'input', 'select', 'date', 'editor'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'users-index',
            'label' => 'Users',
            'icon' => 'bx-user',
            'route' => 'users.index',
            'route_params' => [],
            'active_patterns' => ['users.*'],
            'permission' => 'management.users.view',
            'section' => 'management',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'User management and administration',
                'keywords' => ['users', 'user', 'people', 'accounts', 'management'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'users-create',
            'label' => 'Create User',
            'icon' => 'bx-user-plus',
            'route' => 'users.create',
            'route_params' => [],
            'active_patterns' => ['users.create'],
            'permission' => 'management.users.create',
            'section' => 'management',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add new user to the system',
                'keywords' => ['create', 'add', 'new', 'user', 'register'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'users-logs',
            'label' => 'User Activity Logs',
            'icon' => 'bx-history',
            'route' => 'users.logs',
            'route_params' => [],
            'active_patterns' => ['users.logs', 'users.logs.data', 'users.user-logs', 'users.user-logs.data'],
            'permission' => 'management.users.view',
            'section' => 'management',
            'contexts' => ['search'],
            'search' => [
                'description' => 'View all user activity logs',
                'keywords' => ['logs', 'activity', 'history', 'audit', 'tracking'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'users-trash',
            'label' => 'User Trash',
            'icon' => 'bx-trash',
            'route' => 'users.trash',
            'route_params' => [],
            'active_patterns' => ['users.trash', 'users.trash.data'],
            'permission' => 'management.users.delete',
            'section' => 'management',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Deleted users that can be restored',
                'keywords' => ['trash', 'deleted', 'removed', 'restore', 'users'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'roles-index',
            'label' => 'Role Templates',
            'icon' => 'bx-shield',
            'route' => 'roles.index',
            'route_params' => [],
            'active_patterns' => ['roles.*'],
            'permission' => 'management.roles.view',
            'section' => 'management',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Role and permission management',
                'keywords' => ['roles', 'role', 'permissions', 'rbac', 'access', 'security'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'roles-create',
            'label' => 'Create Role',
            'icon' => 'bx-shield-plus',
            'route' => 'roles.create',
            'route_params' => [],
            'active_patterns' => ['roles.create'],
            'permission' => 'management.roles.create',
            'section' => 'management',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Create new role with permissions',
                'keywords' => ['create', 'add', 'new', 'role', 'permission'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'companies-index',
            'label' => 'Companies',
            'icon' => 'bx-buildings',
            'route' => 'companies.index',
            'route_params' => [],
            'active_patterns' => ['companies.*'],
            'permission' => 'settings.companies.view',
            'section' => 'settings',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Company master data for inventory ownership',
                'keywords' => ['companies', 'company', 'vendor owner', 'organization', 'inventory'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'companies-create',
            'label' => 'Create Company',
            'icon' => 'bx-building-house',
            'route' => 'companies.create',
            'route_params' => [],
            'active_patterns' => ['companies.create'],
            'permission' => 'settings.companies.create',
            'section' => 'settings',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add a new company record',
                'keywords' => ['create', 'add', 'new', 'company'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'categories-index',
            'label' => 'Categories',
            'icon' => 'bx-category',
            'route' => 'categories.index',
            'route_params' => [],
            'active_patterns' => ['categories.*'],
            'permission' => 'settings.categories.view',
            'section' => 'settings',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Category master data for inventory modules',
                'keywords' => ['categories', 'category', 'inventory type', 'classification'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'categories-create',
            'label' => 'Create Category',
            'icon' => 'bx-book-add',
            'route' => 'categories.create',
            'route_params' => [],
            'active_patterns' => ['categories.create'],
            'permission' => 'settings.categories.create',
            'section' => 'settings',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add a new inventory category record',
                'keywords' => ['create', 'add', 'new', 'category'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'manufacturers-index',
            'label' => 'Manufacturers',
            'icon' => 'bx-factory',
            'route' => 'manufacturers.index',
            'route_params' => [],
            'active_patterns' => ['manufacturers.*'],
            'permission' => 'settings.manufacturers.view',
            'section' => 'settings',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Manufacturer master data for inventory modules',
                'keywords' => ['manufacturers', 'manufacturer', 'brand', 'vendor support'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'manufacturers-create',
            'label' => 'Create Manufacturer',
            'icon' => 'bx-building',
            'route' => 'manufacturers.create',
            'route_params' => [],
            'active_patterns' => ['manufacturers.create'],
            'permission' => 'settings.manufacturers.create',
            'section' => 'settings',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add a new manufacturer record',
                'keywords' => ['create', 'add', 'new', 'manufacturer'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'suppliers-index',
            'label' => 'Suppliers',
            'icon' => 'bx-store',
            'route' => 'suppliers.index',
            'route_params' => [],
            'active_patterns' => ['suppliers.*'],
            'permission' => 'settings.suppliers.view',
            'section' => 'settings',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Supplier master data for procurement and inventory',
                'keywords' => ['suppliers', 'supplier', 'vendor', 'procurement', 'purchasing'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'suppliers-create',
            'label' => 'Create Supplier',
            'icon' => 'bx-cart-add',
            'route' => 'suppliers.create',
            'route_params' => [],
            'active_patterns' => ['suppliers.create'],
            'permission' => 'settings.suppliers.create',
            'section' => 'settings',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add a new supplier record',
                'keywords' => ['create', 'add', 'new', 'supplier'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'status-labels-index',
            'label' => 'Status Labels',
            'icon' => 'bx-purchase-tag',
            'route' => 'status-labels.index',
            'route_params' => [],
            'active_patterns' => ['status-labels.*'],
            'permission' => 'settings.status_labels.view',
            'section' => 'settings',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Asset status label master data for inventory modules',
                'keywords' => ['status', 'status label', 'asset status', 'deployable', 'pending', 'archived'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'status-labels-create',
            'label' => 'Create Status Label',
            'icon' => 'bx-label',
            'route' => 'status-labels.create',
            'route_params' => [],
            'active_patterns' => ['status-labels.create'],
            'permission' => 'settings.status_labels.create',
            'section' => 'settings',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add a new asset status label record',
                'keywords' => ['create', 'add', 'new', 'status label'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'custom-fields-index',
            'label' => 'Custom Fields',
            'icon' => 'bx-list-plus',
            'route' => 'custom-fields.index',
            'route_params' => [],
            'active_patterns' => ['custom-fields.*'],
            'permission' => 'settings.custom_fields.view',
            'section' => 'settings',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Custom field definitions for asset model metadata',
                'keywords' => ['custom field', 'field', 'metadata', 'asset field', 'custom'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'custom-fields-create',
            'label' => 'Create Custom Field',
            'icon' => 'bx-list-plus',
            'route' => 'custom-fields.create',
            'route_params' => [],
            'active_patterns' => ['custom-fields.create'],
            'permission' => 'settings.custom_fields.create',
            'section' => 'settings',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add a new custom field definition',
                'keywords' => ['create', 'add', 'new', 'custom field'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'custom-fieldsets-index',
            'label' => 'Custom Fieldsets',
            'icon' => 'bx-collection',
            'route' => 'custom-fieldsets.index',
            'route_params' => [],
            'active_patterns' => ['custom-fieldsets.*'],
            'permission' => 'settings.custom_fieldsets.view',
            'section' => 'settings',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Custom fieldset groups for asset model custom field layout',
                'keywords' => ['fieldset', 'custom fieldset', 'field group', 'asset fieldset'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'custom-fieldsets-create',
            'label' => 'Create Custom Fieldset',
            'icon' => 'bx-collection',
            'route' => 'custom-fieldsets.create',
            'route_params' => [],
            'active_patterns' => ['custom-fieldsets.create'],
            'permission' => 'settings.custom_fieldsets.create',
            'section' => 'settings',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add a new custom fieldset group',
                'keywords' => ['create', 'add', 'new', 'fieldset', 'custom fieldset'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'locations-index',
            'label' => 'Locations',
            'icon' => 'bx-map-alt',
            'route' => 'locations.index',
            'route_params' => [],
            'active_patterns' => ['locations.*'],
            'permission' => 'settings.locations.view',
            'section' => 'settings',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Branch, site, and location master data for inventory',
                'keywords' => ['location', 'lokasi', 'branch', 'site', 'cabang', 'gedung'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'locations-create',
            'label' => 'Create Location',
            'icon' => 'bx-map-alt',
            'route' => 'locations.create',
            'route_params' => [],
            'active_patterns' => ['locations.create'],
            'permission' => 'settings.locations.create',
            'section' => 'settings',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add a new location or branch record',
                'keywords' => ['create', 'add', 'new', 'location', 'lokasi', 'cabang'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'departments-index',
            'label' => 'Departments',
            'icon' => 'bx-briefcase',
            'route' => 'departments.index',
            'route_params' => [],
            'active_patterns' => ['departments.*'],
            'permission' => 'settings.departments.view',
            'section' => 'settings',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Manage organizational departments for inventory',
                'keywords' => ['department', 'departemen', 'divisi', 'organisasi'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'departments-create',
            'label' => 'Create Department',
            'icon' => 'bx-briefcase',
            'route' => 'departments.create',
            'route_params' => [],
            'active_patterns' => ['departments.create'],
            'permission' => 'settings.departments.create',
            'section' => 'settings',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add a new department record',
                'keywords' => ['create', 'add', 'new', 'department', 'departemen', 'divisi'],
            ],
            'enabled' => true,
        ],
    ],
];
