<?php

return [
    'sections' => [
        'general' => [
            'label' => 'General',
            'order' => 10,
            'contexts' => ['desktop', 'search'],
        ],
        'library' => [
            'label' => 'Library',
            'order' => 20,
            'contexts' => ['desktop', 'search'],
        ],
        'master-data' => [
            'label' => 'Master Data',
            'order' => 30,
            'contexts' => ['desktop', 'search'],
        ],
        'management' => [
            'label' => 'Management',
            'order' => 40,
            'contexts' => ['desktop', 'search'],
        ],
    ],

    'items' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'icon' => 'bx-home-smile',
            'route' => 'home',
            'route_params' => [],
            'active_patterns' => ['home'],
            'permission' => null,
            'section' => 'general',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Main dashboard overview',
                'keywords' => ['dashboard', 'home', 'main', 'overview'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'mobile',
            'label' => 'Mobile',
            'icon' => 'bx-mobile',
            'route' => 'mobile.index',
            'route_params' => [],
            'active_patterns' => ['mobile.*'],
            'permission' => null,
            'section' => 'general',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Mobile application features',
                'keywords' => ['mobile', 'app', 'phone', 'device'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'images-index',
            'label' => 'Image Gallery',
            'icon' => 'bx-image',
            'route' => 'images.index',
            'route_params' => [],
            'active_patterns' => ['images.*'],
            'permission' => 'images.view',
            'section' => 'library',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Browse and manage image assets',
                'keywords' => ['images', 'image', 'gallery', 'asset', 'library'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'categories-index',
            'label' => 'Categories',
            'icon' => 'bx-category',
            'route' => 'categories.index',
            'route_params' => [],
            'active_patterns' => ['categories.*'],
            'permission' => 'master.categories.view',
            'section' => 'master-data',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Manage product categories',
                'keywords' => ['categories', 'category', 'master', 'catalog'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'products-index',
            'label' => 'Products',
            'icon' => 'bx-package',
            'route' => 'products.index',
            'route_params' => [],
            'active_patterns' => ['products.*'],
            'permission' => 'master.products.view',
            'section' => 'master-data',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Manage product master data',
                'keywords' => ['products', 'product', 'master', 'catalog', 'inventory'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'products-esb-index',
            'label' => 'Sync Product ESB',
            'icon' => 'bx-cloud-download',
            'route' => 'products-esb.index',
            'route_params' => [],
            'active_patterns' => ['products-esb.*'],
            'permission' => 'master.products_esb.view',
            'section' => 'master-data',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Sync and review products from ESB',
                'keywords' => ['product', 'esb', 'sync', 'master', 'products'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'employees-index',
            'label' => 'Master Employee',
            'icon' => 'bx-id-card',
            'route' => 'employees.index',
            'route_params' => [],
            'active_patterns' => ['employees.*'],
            'permission' => 'master.employees.view',
            'section' => 'master-data',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Employee master data and JPayroll sync',
                'keywords' => ['employee', 'employees', 'master', 'jpayroll', 'sync', 'staff'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'users-index',
            'label' => 'Users',
            'icon' => 'bx-user',
            'route' => 'users.index',
            'route_params' => [],
            'active_patterns' => ['users.*'],
            'permission' => 'management.users.view',
            'section' => 'management',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'User management and administration',
                'keywords' => ['users', 'user', 'people', 'accounts', 'management'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'users-create',
            'label' => 'Create User',
            'icon' => 'bx-user-plus',
            'route' => 'users.create',
            'route_params' => [],
            'active_patterns' => ['users.create'],
            'permission' => 'management.users.create',
            'section' => 'management',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Add new user to the system',
                'keywords' => ['create', 'add', 'new', 'user', 'register'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'users-logs',
            'label' => 'User Activity Logs',
            'icon' => 'bx-history',
            'route' => 'users.logs',
            'route_params' => [],
            'active_patterns' => ['users.logs', 'users.logs.data', 'users.user-logs', 'users.user-logs.data'],
            'permission' => 'management.users.view',
            'section' => 'management',
            'contexts' => ['search'],
            'search' => [
                'description' => 'View all user activity logs',
                'keywords' => ['logs', 'activity', 'history', 'audit', 'tracking'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'users-trash',
            'label' => 'User Trash',
            'icon' => 'bx-trash',
            'route' => 'users.trash',
            'route_params' => [],
            'active_patterns' => ['users.trash', 'users.trash.data'],
            'permission' => 'management.users.delete',
            'section' => 'management',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Deleted users that can be restored',
                'keywords' => ['trash', 'deleted', 'removed', 'restore', 'users'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'roles-index',
            'label' => 'Role Templates',
            'icon' => 'bx-shield',
            'route' => 'roles.index',
            'route_params' => [],
            'active_patterns' => ['roles.*'],
            'permission' => 'management.roles.view',
            'section' => 'management',
            'contexts' => ['desktop', 'search'],
            'search' => [
                'description' => 'Role and permission management',
                'keywords' => ['roles', 'role', 'permissions', 'rbac', 'access', 'security'],
            ],
            'enabled' => true,
        ],
        [
            'key' => 'roles-create',
            'label' => 'Create Role',
            'icon' => 'bx-shield-plus',
            'route' => 'roles.create',
            'route_params' => [],
            'active_patterns' => ['roles.create'],
            'permission' => 'management.roles.create',
            'section' => 'management',
            'contexts' => ['search'],
            'search' => [
                'description' => 'Create new role with permissions',
                'keywords' => ['create', 'add', 'new', 'role', 'permission'],
            ],
            'enabled' => true,
        ],
    ],
];
