<?php

return [
    'permissions' => [
        'management' => [
            'sort_order' => 1,
            'items' => [
                [
                    'name' => 'management.access',
                    'display_name' => 'Management',
                    'description' => 'Can access Management section',
                    'module' => 'management',
                    'parent' => null,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'management.users.view',
                    'display_name' => 'Users - View',
                    'description' => 'Can view users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 2,
                ],
                [
                    'name' => 'management.users.create',
                    'display_name' => 'Users - Create',
                    'description' => 'Can create users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 3,
                ],
                [
                    'name' => 'management.users.edit',
                    'display_name' => 'Users - Edit',
                    'description' => 'Can edit users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 4,
                ],
                [
                    'name' => 'management.users.delete',
                    'display_name' => 'Users - Delete',
                    'description' => 'Can delete users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 5,
                ],
                [
                    'name' => 'management.users.restore',
                    'display_name' => 'Users - Restore',
                    'description' => 'Can restore deleted users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 6,
                ],
                [
                    'name' => 'management.users.force_delete',
                    'display_name' => 'Users - Force Delete',
                    'description' => 'Can permanently delete users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 7,
                ],
                [
                    'name' => 'management.users.logs',
                    'display_name' => 'Users - View Logs',
                    'description' => 'Can view user activity logs',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 8,
                ],
                [
                    'name' => 'management.users.permissions',
                    'display_name' => 'Users - Manage Permissions',
                    'description' => 'Can manage user permissions directly',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 9,
                ],
                [
                    'name' => 'management.roles.view',
                    'display_name' => 'Role Templates - View',
                    'description' => 'Can view role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 10,
                ],
                [
                    'name' => 'management.roles.create',
                    'display_name' => 'Role Templates - Create',
                    'description' => 'Can create role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 11,
                ],
                [
                    'name' => 'management.roles.edit',
                    'display_name' => 'Role Templates - Edit',
                    'description' => 'Can edit role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 12,
                ],
                [
                    'name' => 'management.roles.delete',
                    'display_name' => 'Role Templates - Delete',
                    'description' => 'Can delete role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 13,
                ],
            ],
        ],
        'inventory' => [
            'sort_order' => 2,
            'items' => [
                [
                    'name' => 'inventory.access',
                    'display_name' => 'Inventory',
                    'description' => 'Can access Inventory section',
                    'module' => 'inventory',
                    'parent' => null,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'inventory.companies.view',
                    'display_name' => 'Companies - View',
                    'description' => 'Can view companies',
                    'module' => 'inventory',
                    'parent' => 'inventory.access',
                    'sort_order' => 2,
                ],
                [
                    'name' => 'inventory.companies.create',
                    'display_name' => 'Companies - Create',
                    'description' => 'Can create companies',
                    'module' => 'inventory',
                    'parent' => 'inventory.access',
                    'sort_order' => 3,
                ],
                [
                    'name' => 'inventory.companies.edit',
                    'display_name' => 'Companies - Edit',
                    'description' => 'Can edit companies',
                    'module' => 'inventory',
                    'parent' => 'inventory.access',
                    'sort_order' => 4,
                ],
                [
                    'name' => 'inventory.companies.delete',
                    'display_name' => 'Companies - Delete',
                    'description' => 'Can delete companies',
                    'module' => 'inventory',
                    'parent' => 'inventory.access',
                    'sort_order' => 5,
                ],
                [
                    'name' => 'inventory.categories.view',
                    'display_name' => 'Categories - View',
                    'description' => 'Can view categories',
                    'module' => 'inventory',
                    'parent' => 'inventory.access',
                    'sort_order' => 6,
                ],
                [
                    'name' => 'inventory.categories.create',
                    'display_name' => 'Categories - Create',
                    'description' => 'Can create categories',
                    'module' => 'inventory',
                    'parent' => 'inventory.access',
                    'sort_order' => 7,
                ],
                [
                    'name' => 'inventory.categories.edit',
                    'display_name' => 'Categories - Edit',
                    'description' => 'Can edit categories',
                    'module' => 'inventory',
                    'parent' => 'inventory.access',
                    'sort_order' => 8,
                ],
                [
                    'name' => 'inventory.categories.delete',
                    'display_name' => 'Categories - Delete',
                    'description' => 'Can delete categories',
                    'module' => 'inventory',
                    'parent' => 'inventory.access',
                    'sort_order' => 9,
                ],
            ],
        ],
    ],
    'role_templates' => [
        [
            'name' => 'super_admin_template',
            'display_name' => 'Super Administrator Template',
            'description' => 'Template with full system access - all permissions',
            'permissions' => ['*'],
        ],
        [
            'name' => 'admin_template',
            'display_name' => 'Administrator Template',
            'description' => 'Template with management access and most features',
            'permissions' => [
                'management.access',
                'management.users.view',
                'management.users.create',
                'management.users.edit',
                'management.users.delete',
                'management.users.restore',
                'management.users.logs',
                'management.roles.view',
                'management.roles.create',
                'management.roles.edit',
                'inventory.access',
                'inventory.companies.view',
                'inventory.companies.create',
                'inventory.companies.edit',
                'inventory.companies.delete',
                'inventory.categories.view',
                'inventory.categories.create',
                'inventory.categories.edit',
                'inventory.categories.delete',
            ],
        ],
        [
            'name' => 'user_manager_template',
            'display_name' => 'User Manager Template',
            'description' => 'Template for user management focus',
            'permissions' => [
                'management.access',
                'management.users.view',
                'management.users.create',
                'management.users.edit',
                'management.users.logs',
                'management.roles.view',
                'inventory.access',
                'inventory.companies.view',
                'inventory.categories.view',
            ],
        ],
        [
            'name' => 'viewer_template',
            'display_name' => 'Viewer Template',
            'description' => 'Template for read-only access',
            'permissions' => [
                'management.access',
                'management.users.view',
                'inventory.access',
                'inventory.companies.view',
                'inventory.categories.view',
            ],
        ],
    ],
    'super_admin_user' => [
        'name' => 'STAGING PURPOSE',
        'username' => 'stagingpurpose',
        'email' => 'staging@tongtji.com',
        'password' => 'P@ssw0rd1938',
        'role' => 'super_admin_template',
    ],
];
