<?php

return [
    'permissions' => [
        'management' => [
            'sort_order' => 1,
            'items' => [
                [
                    'name' => 'management.access',
                    'display_name' => 'Management',
                    'description' => 'Can access Management section',
                    'module' => 'management',
                    'parent' => null,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'management.users.view',
                    'display_name' => 'Users - View',
                    'description' => 'Can view users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 2,
                ],
                [
                    'name' => 'management.users.create',
                    'display_name' => 'Users - Create',
                    'description' => 'Can create users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 3,
                ],
                [
                    'name' => 'management.users.edit',
                    'display_name' => 'Users - Edit',
                    'description' => 'Can edit users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 4,
                ],
                [
                    'name' => 'management.users.delete',
                    'display_name' => 'Users - Delete',
                    'description' => 'Can delete users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 5,
                ],
                [
                    'name' => 'management.users.restore',
                    'display_name' => 'Users - Restore',
                    'description' => 'Can restore deleted users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 6,
                ],
                [
                    'name' => 'management.users.force_delete',
                    'display_name' => 'Users - Force Delete',
                    'description' => 'Can permanently delete users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 7,
                ],
                [
                    'name' => 'management.users.logs',
                    'display_name' => 'Users - View Logs',
                    'description' => 'Can view user activity logs',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 8,
                ],
                [
                    'name' => 'management.users.permissions',
                    'display_name' => 'Users - Manage Permissions',
                    'description' => 'Can manage user permissions directly',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 9,
                ],
                [
                    'name' => 'management.roles.view',
                    'display_name' => 'Role Templates - View',
                    'description' => 'Can view role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 10,
                ],
                [
                    'name' => 'management.roles.create',
                    'display_name' => 'Role Templates - Create',
                    'description' => 'Can create role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 11,
                ],
                [
                    'name' => 'management.roles.edit',
                    'display_name' => 'Role Templates - Edit',
                    'description' => 'Can edit role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 12,
                ],
                [
                    'name' => 'management.roles.delete',
                    'display_name' => 'Role Templates - Delete',
                    'description' => 'Can delete role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 13,
                ],
            ],
        ],
        'images' => [
            'sort_order' => 2,
            'items' => [
                [
                    'name' => 'images.access',
                    'display_name' => 'Images',
                    'description' => 'Can access Images section',
                    'module' => 'images',
                    'parent' => null,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'images.view',
                    'display_name' => 'Images - View',
                    'description' => 'Can view images',
                    'module' => 'images',
                    'parent' => 'images.access',
                    'sort_order' => 2,
                ],
                [
                    'name' => 'images.create',
                    'display_name' => 'Images - Upload',
                    'description' => 'Can upload images',
                    'module' => 'images',
                    'parent' => 'images.access',
                    'sort_order' => 3,
                ],
                [
                    'name' => 'images.edit',
                    'display_name' => 'Images - Edit',
                    'description' => 'Can edit images',
                    'module' => 'images',
                    'parent' => 'images.access',
                    'sort_order' => 4,
                ],
                [
                    'name' => 'images.delete',
                    'display_name' => 'Images - Delete',
                    'description' => 'Can delete images',
                    'module' => 'images',
                    'parent' => 'images.access',
                    'sort_order' => 5,
                ],
                [
                    'name' => 'images.restore',
                    'display_name' => 'Images - Restore',
                    'description' => 'Can restore deleted images',
                    'module' => 'images',
                    'parent' => 'images.access',
                    'sort_order' => 6,
                ],
                [
                    'name' => 'images.force_delete',
                    'display_name' => 'Images - Force Delete',
                    'description' => 'Can permanently delete images',
                    'module' => 'images',
                    'parent' => 'images.access',
                    'sort_order' => 7,
                ],
            ],
        ],
        'master' => [
            'sort_order' => 3,
            'items' => [
                [
                    'name' => 'master.access',
                    'display_name' => 'Master Data',
                    'description' => 'Can access Master Data section',
                    'module' => 'master',
                    'parent' => null,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'master.categories.view',
                    'display_name' => 'Categories - View',
                    'description' => 'Can view categories',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 2,
                ],
                [
                    'name' => 'master.categories.create',
                    'display_name' => 'Categories - Create',
                    'description' => 'Can create categories',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 3,
                ],
                [
                    'name' => 'master.categories.edit',
                    'display_name' => 'Categories - Edit',
                    'description' => 'Can edit categories',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 4,
                ],
                [
                    'name' => 'master.categories.delete',
                    'display_name' => 'Categories - Delete',
                    'description' => 'Can delete categories',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 5,
                ],
                [
                    'name' => 'master.categories.restore',
                    'display_name' => 'Categories - Restore',
                    'description' => 'Can restore deleted categories',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 6,
                ],
                [
                    'name' => 'master.categories.force_delete',
                    'display_name' => 'Categories - Force Delete',
                    'description' => 'Can permanently delete categories',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 7,
                ],
                [
                    'name' => 'master.products.view',
                    'display_name' => 'Products - View',
                    'description' => 'Can view products',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 8,
                ],
                [
                    'name' => 'master.products.create',
                    'display_name' => 'Products - Create',
                    'description' => 'Can create products',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 9,
                ],
                [
                    'name' => 'master.products.edit',
                    'display_name' => 'Products - Edit',
                    'description' => 'Can edit products',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 10,
                ],
                [
                    'name' => 'master.products.delete',
                    'display_name' => 'Products - Delete',
                    'description' => 'Can delete products',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 11,
                ],
                [
                    'name' => 'master.products.restore',
                    'display_name' => 'Products - Restore',
                    'description' => 'Can restore deleted products',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 12,
                ],
                [
                    'name' => 'master.products.force_delete',
                    'display_name' => 'Products - Force Delete',
                    'description' => 'Can permanently delete products',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 13,
                ],
                [
                    'name' => 'master.products_esb.view',
                    'display_name' => 'Products ESB - View',
                    'description' => 'Can view ESB products',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 14,
                ],
                [
                    'name' => 'master.products_esb.sync',
                    'display_name' => 'Products ESB - Sync',
                    'description' => 'Can sync products from ESB',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 15,
                ],
                [
                    'name' => 'master.employees.view',
                    'display_name' => 'Employees - View',
                    'description' => 'Can view employees',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 16,
                ],
                [
                    'name' => 'master.employees.sync',
                    'display_name' => 'Employees - Sync',
                    'description' => 'Can sync employees from JPayroll',
                    'module' => 'master',
                    'parent' => 'master.access',
                    'sort_order' => 17,
                ],
            ],
        ],
    ],
    'role_templates' => [
        [
            'name' => 'super_admin_template',
            'display_name' => 'Super Administrator Template',
            'description' => 'Template with full system access - all permissions',
            'permissions' => ['*'],
        ],
        [
            'name' => 'admin_template',
            'display_name' => 'Administrator Template',
            'description' => 'Template with management access and most features',
            'permissions' => [
                'management.access',
                'management.users.view',
                'management.users.create',
                'management.users.edit',
                'management.users.delete',
                'management.users.restore',
                'management.users.logs',
                'management.roles.view',
                'management.roles.create',
                'management.roles.edit',
                'images.access',
                'images.view',
                'images.create',
                'images.edit',
                'images.delete',
                'images.restore',
                'master.access',
                'master.categories.view',
                'master.categories.create',
                'master.categories.edit',
                'master.categories.delete',
                'master.categories.restore',
                'master.products.view',
                'master.products.create',
                'master.products.edit',
                'master.products.delete',
                'master.products.restore',
                'master.products_esb.view',
                'master.products_esb.sync',
                'master.employees.view',
                'master.employees.sync',
            ],
        ],
        [
            'name' => 'user_manager_template',
            'display_name' => 'User Manager Template',
            'description' => 'Template for user management focus',
            'permissions' => [
                'management.access',
                'management.users.view',
                'management.users.create',
                'management.users.edit',
                'management.users.logs',
                'management.roles.view',
            ],
        ],
        [
            'name' => 'viewer_template',
            'display_name' => 'Viewer Template',
            'description' => 'Template for read-only access',
            'permissions' => [
                'management.access',
                'management.users.view',
                'master.access',
                'master.categories.view',
                'master.products.view',
                'master.products_esb.view',
                'master.employees.view',
            ],
        ],
    ],
    'super_admin_user' => [
        'name' => 'STAGING PURPOSE',
        'username' => 'stagingpurpose',
        'email' => 'staging@tongtji.com',
        'password' => 'P@ssw0rd1938',
        'role' => 'super_admin_template',
    ],
];
