<?php

return [
    'permissions' => [
        'management' => [
            'sort_order' => 1,
            'items' => [
                [
                    'name' => 'management.access',
                    'display_name' => 'Management',
                    'description' => 'Can access Management section',
                    'module' => 'management',
                    'parent' => null,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'management.users.view',
                    'display_name' => 'Users - View',
                    'description' => 'Can view users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 2,
                ],
                [
                    'name' => 'management.users.create',
                    'display_name' => 'Users - Create',
                    'description' => 'Can create users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 3,
                ],
                [
                    'name' => 'management.users.edit',
                    'display_name' => 'Users - Edit',
                    'description' => 'Can edit users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 4,
                ],
                [
                    'name' => 'management.users.delete',
                    'display_name' => 'Users - Delete',
                    'description' => 'Can delete users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 5,
                ],
                [
                    'name' => 'management.users.restore',
                    'display_name' => 'Users - Restore',
                    'description' => 'Can restore deleted users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 6,
                ],
                [
                    'name' => 'management.users.force_delete',
                    'display_name' => 'Users - Force Delete',
                    'description' => 'Can permanently delete users',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 7,
                ],
                [
                    'name' => 'management.users.logs',
                    'display_name' => 'Users - View Logs',
                    'description' => 'Can view user activity logs',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 8,
                ],
                [
                    'name' => 'management.users.permissions',
                    'display_name' => 'Users - Manage Permissions',
                    'description' => 'Can manage user permissions directly',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 9,
                ],
                [
                    'name' => 'management.roles.view',
                    'display_name' => 'Role Templates - View',
                    'description' => 'Can view role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 10,
                ],
                [
                    'name' => 'management.roles.create',
                    'display_name' => 'Role Templates - Create',
                    'description' => 'Can create role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 11,
                ],
                [
                    'name' => 'management.roles.edit',
                    'display_name' => 'Role Templates - Edit',
                    'description' => 'Can edit role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 12,
                ],
                [
                    'name' => 'management.roles.delete',
                    'display_name' => 'Role Templates - Delete',
                    'description' => 'Can delete role templates',
                    'module' => 'management',
                    'parent' => 'management.access',
                    'sort_order' => 13,
                ],
            ],
        ],
        'settings' => [
            'sort_order' => 2,
            'items' => [
                [
                    'name' => 'settings.access',
                    'display_name' => 'Settings',
                    'description' => 'Can access Settings section',
                    'module' => 'settings',
                    'parent' => null,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'settings.companies.view',
                    'display_name' => 'Companies - View',
                    'description' => 'Can view companies',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 2,
                ],
                [
                    'name' => 'settings.companies.create',
                    'display_name' => 'Companies - Create',
                    'description' => 'Can create companies',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 3,
                ],
                [
                    'name' => 'settings.companies.edit',
                    'display_name' => 'Companies - Edit',
                    'description' => 'Can edit companies',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 4,
                ],
                [
                    'name' => 'settings.companies.delete',
                    'display_name' => 'Companies - Delete',
                    'description' => 'Can delete companies',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 5,
                ],
                [
                    'name' => 'settings.categories.view',
                    'display_name' => 'Categories - View',
                    'description' => 'Can view categories',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 6,
                ],
                [
                    'name' => 'settings.categories.create',
                    'display_name' => 'Categories - Create',
                    'description' => 'Can create categories',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 7,
                ],
                [
                    'name' => 'settings.categories.edit',
                    'display_name' => 'Categories - Edit',
                    'description' => 'Can edit categories',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 8,
                ],
                [
                    'name' => 'settings.categories.delete',
                    'display_name' => 'Categories - Delete',
                    'description' => 'Can delete categories',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 9,
                ],
                [
                    'name' => 'settings.manufacturers.view',
                    'display_name' => 'Manufacturers - View',
                    'description' => 'Can view manufacturers',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 10,
                ],
                [
                    'name' => 'settings.manufacturers.create',
                    'display_name' => 'Manufacturers - Create',
                    'description' => 'Can create manufacturers',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 11,
                ],
                [
                    'name' => 'settings.manufacturers.edit',
                    'display_name' => 'Manufacturers - Edit',
                    'description' => 'Can edit manufacturers',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 12,
                ],
                [
                    'name' => 'settings.manufacturers.delete',
                    'display_name' => 'Manufacturers - Delete',
                    'description' => 'Can delete manufacturers',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 13,
                ],
                [
                    'name' => 'settings.suppliers.view',
                    'display_name' => 'Suppliers - View',
                    'description' => 'Can view suppliers',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 14,
                ],
                [
                    'name' => 'settings.suppliers.create',
                    'display_name' => 'Suppliers - Create',
                    'description' => 'Can create suppliers',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 15,
                ],
                [
                    'name' => 'settings.suppliers.edit',
                    'display_name' => 'Suppliers - Edit',
                    'description' => 'Can edit suppliers',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 16,
                ],
                [
                    'name' => 'settings.suppliers.delete',
                    'display_name' => 'Suppliers - Delete',
                    'description' => 'Can delete suppliers',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 17,
                ],
                [
                    'name' => 'settings.status_labels.view',
                    'display_name' => 'Status Labels - View',
                    'description' => 'Can view status labels',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 18,
                ],
                [
                    'name' => 'settings.status_labels.create',
                    'display_name' => 'Status Labels - Create',
                    'description' => 'Can create status labels',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 19,
                ],
                [
                    'name' => 'settings.status_labels.edit',
                    'display_name' => 'Status Labels - Edit',
                    'description' => 'Can edit status labels',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 20,
                ],
                [
                    'name' => 'settings.status_labels.delete',
                    'display_name' => 'Status Labels - Delete',
                    'description' => 'Can delete status labels',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 21,
                ],
                [
                    'name' => 'settings.custom_fields.view',
                    'display_name' => 'Custom Fields - View',
                    'description' => 'Can view custom fields',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 22,
                ],
                [
                    'name' => 'settings.custom_fields.create',
                    'display_name' => 'Custom Fields - Create',
                    'description' => 'Can create custom fields',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 23,
                ],
                [
                    'name' => 'settings.custom_fields.edit',
                    'display_name' => 'Custom Fields - Edit',
                    'description' => 'Can edit custom fields',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 24,
                ],
                [
                    'name' => 'settings.custom_fields.delete',
                    'display_name' => 'Custom Fields - Delete',
                    'description' => 'Can delete custom fields',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 25,
                ],
                [
                    'name' => 'settings.custom_fieldsets.view',
                    'display_name' => 'Custom Fieldsets - View',
                    'description' => 'Can view custom fieldsets',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 26,
                ],
                [
                    'name' => 'settings.custom_fieldsets.create',
                    'display_name' => 'Custom Fieldsets - Create',
                    'description' => 'Can create custom fieldsets',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 27,
                ],
                [
                    'name' => 'settings.custom_fieldsets.edit',
                    'display_name' => 'Custom Fieldsets - Edit',
                    'description' => 'Can edit custom fieldsets',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 28,
                ],
                [
                    'name' => 'settings.custom_fieldsets.delete',
                    'display_name' => 'Custom Fieldsets - Delete',
                    'description' => 'Can delete custom fieldsets',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 29,
                ],
                [
                    'name' => 'settings.locations.view',
                    'display_name' => 'Locations - View',
                    'description' => 'Can view locations',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 30,
                ],
                [
                    'name' => 'settings.locations.create',
                    'display_name' => 'Locations - Create',
                    'description' => 'Can create locations',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 31,
                ],
                [
                    'name' => 'settings.locations.edit',
                    'display_name' => 'Locations - Edit',
                    'description' => 'Can edit locations',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 32,
                ],
                [
                    'name' => 'settings.locations.delete',
                    'display_name' => 'Locations - Delete',
                    'description' => 'Can delete locations',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 33,
                ],
                [
                    'name' => 'settings.departments.view',
                    'display_name' => 'Departments - View',
                    'description' => 'Can view departments',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 34,
                ],
                [
                    'name' => 'settings.departments.create',
                    'display_name' => 'Departments - Create',
                    'description' => 'Can create departments',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 35,
                ],
                [
                    'name' => 'settings.departments.edit',
                    'display_name' => 'Departments - Edit',
                    'description' => 'Can edit departments',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 36,
                ],
                [
                    'name' => 'settings.departments.delete',
                    'display_name' => 'Departments - Delete',
                    'description' => 'Can delete departments',
                    'module' => 'settings',
                    'parent' => 'settings.access',
                    'sort_order' => 37,
                ],
            ],
        ],
        'inventory' => [
            'sort_order' => 3,
            'items' => [
                [
                    'name' => 'inventory.access',
                    'display_name' => 'Inventory',
                    'description' => 'Can access Inventory section',
                    'module' => 'inventory',
                    'parent' => null,
                    'sort_order' => 1,
                ],
            ],
        ],
    ],
    'role_templates' => [
        [
            'name' => 'super_admin_template',
            'display_name' => 'Super Administrator Template',
            'description' => 'Template with full system access - all permissions',
            'permissions' => ['*'],
        ],
        [
            'name' => 'admin_template',
            'display_name' => 'Administrator Template',
            'description' => 'Template with management access and most features',
            'permissions' => [
                'management.access',
                'management.users.view',
                'management.users.create',
                'management.users.edit',
                'management.users.delete',
                'management.users.restore',
                'management.users.logs',
                'management.roles.view',
                'management.roles.create',
                'management.roles.edit',
                'settings.access',
                'settings.companies.view',
                'settings.companies.create',
                'settings.companies.edit',
                'settings.companies.delete',
                'settings.categories.view',
                'settings.categories.create',
                'settings.categories.edit',
                'settings.categories.delete',
                'settings.manufacturers.view',
                'settings.manufacturers.create',
                'settings.manufacturers.edit',
                'settings.manufacturers.delete',
                'settings.suppliers.view',
                'settings.suppliers.create',
                'settings.suppliers.edit',
                'settings.suppliers.delete',
                'settings.status_labels.view',
                'settings.status_labels.create',
                'settings.status_labels.edit',
                'settings.status_labels.delete',
                'settings.custom_fields.view',
                'settings.custom_fields.create',
                'settings.custom_fields.edit',
                'settings.custom_fields.delete',
                'settings.custom_fieldsets.view',
                'settings.custom_fieldsets.create',
                'settings.custom_fieldsets.edit',
                'settings.custom_fieldsets.delete',
                'settings.locations.view',
                'settings.locations.create',
                'settings.locations.edit',
                'settings.locations.delete',
                'settings.departments.view',
                'settings.departments.create',
                'settings.departments.edit',
                'settings.departments.delete',
                'inventory.access',
            ],
        ],
        [
            'name' => 'user_manager_template',
            'display_name' => 'User Manager Template',
            'description' => 'Template for user management focus',
            'permissions' => [
                'management.access',
                'management.users.view',
                'management.users.create',
                'management.users.edit',
                'management.users.logs',
                'management.roles.view',
                'settings.access',
                'settings.companies.view',
                'settings.categories.view',
                'settings.manufacturers.view',
                'settings.suppliers.view',
                'settings.status_labels.view',
                'settings.custom_fields.view',
                'settings.custom_fieldsets.view',
                'settings.locations.view',
                'settings.departments.view',
                'inventory.access',
            ],
        ],
        [
            'name' => 'viewer_template',
            'display_name' => 'Viewer Template',
            'description' => 'Template for read-only access',
            'permissions' => [
                'management.access',
                'management.users.view',
                'settings.access',
                'settings.companies.view',
                'settings.categories.view',
                'settings.manufacturers.view',
                'settings.suppliers.view',
                'settings.status_labels.view',
                'settings.custom_fields.view',
                'settings.custom_fieldsets.view',
                'settings.locations.view',
                'settings.departments.view',
                'inventory.access',
            ],
        ],
    ],
    'super_admin_user' => [
        'name' => 'STAGING PURPOSE',
        'username' => 'stagingpurpose',
        'email' => 'staging@tongtji.com',
        'password' => 'P@ssw0rd1938',
        'role' => 'super_admin_template',
    ],
];
